name: Staging
run-name: Run CI/CD Cycle for Staging Environment
on:
  push:
    branches:
      - develop
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job is triggered by a push to the develop branch"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup .env file
        run: echo "CI_ENVIRONMENT=development" >> .env && echo "app.baseURL='http://example.com'" >> .env
      - name: Show .env file
        run: cat .env
      - name: Set permissions for logs directory recursively to avoid permission errors
        run: chmod -R 777 ${{ github.workspace }}/writable/logs
      - name: Install dependencies
        run: composer install
      - name: Run PHPUnit tests
        run: ${{ github.workspace }}/vendor/bin/phpunit
